# Generated by Django 4.2 on 2023-04-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0002_remove_user_country_remove_user_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
