# Generated by Django 4.2 on 2023-04-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0006_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
    ]
