# Generated by Django 4.2 on 2023-04-22 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0010_remove_quote_text_quote_quote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
