# Generated by Django 4.2 on 2023-04-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0012_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='text',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote',
            field=models.CharField(default='', max_length=200),
        ),
    ]
