# Generated by Django 4.2 on 2023-04-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0013_remove_quote_text_quote_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote',
            new_name='title',
        ),
    ]
