# Generated by Django 4.2 on 2023-04-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0014_rename_quote_quote_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
