# Generated by Django 4.2 on 2023-04-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0016_qoute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qoute',
        ),
    ]
