# Generated by Django 4.2 on 2023-04-24 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0019_gratitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratitude',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
