# Generated by Django 4.2 on 2023-04-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0022_account_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
