# Generated by Django 4.2 on 2023-04-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0024_profile_balance_profile_expenses_profile_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='income',
            field=models.FloatField(),
        ),
    ]
