# Generated by Django 4.2 on 2023-04-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0026_alter_profile_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='income',
            field=models.FloatField(default=0),
        ),
    ]
